name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      # Runs a single command using the runners shell
    - name: Build Docker Image
      run: | 
          docker login -u="nilave" -p="$SSH_KEY"
          docker build -t nilave/toolzilla-mongodb:latest .
          docker push nilave/toolzilla-mongodb:latest
      env:
          SSH_KEY: ${{secrets.DOCKER_PASSWORD}}
